version: '3.8'

services:
  redis:
    image: 'redis:latest'
    container_name: 'sportscenter-redis'
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data

  redis-commander:
    image: ghcr.io/joeferner/redis-commander:latest    
    container_name: 'sportscenter-redis-commander'
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - '8081:8081'

volumes:
  redis-data:
